apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tic-tac-toe-ing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: "nginx"
  rules:
    - host: tic.anyeweb.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tic-tac-toe-svc
                port:
                  number: 80
